/*
 * Best Buy API Playground
 * A sample dataset and API for you to experiment with.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@bestbuy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import com.google.gson.reflect.TypeToken;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.builder.ResponseSpecBuilder;
import io.restassured.http.Method;
import io.restassured.response.Response;
import io.swagger.annotations.*;

import java.lang.reflect.Type;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;
import org.openapitools.client.JSON;

import static io.restassured.http.Method.*;

@Api(value = "Utilities")
public class UtilitiesApi {

    private RequestSpecBuilder reqSpec;

    private UtilitiesApi(RequestSpecBuilder reqSpec) {
        this.reqSpec = reqSpec;
    }

    public static UtilitiesApi utilities(RequestSpecBuilder reqSpec) {
        return new UtilitiesApi(reqSpec);
    }


    @ApiOperation(value = "",
            notes = "Returns healthcheck information about the system",
            nickname = "getHealthcheck",
            tags = { "utilities" })
    @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Healthcheck response") ,
            @ApiResponse(code = 500, message = "Error")  })
    public GetHealthcheckOper getHealthcheck() {
        return new GetHealthcheckOper(reqSpec);
    }

    @ApiOperation(value = "",
            notes = "Returns the current version of the API Playground being run",
            nickname = "getVersion",
            tags = { "utilities" })
    @ApiResponses(value = { 
            @ApiResponse(code = 200, message = "Version response")  })
    public GetVersionOper getVersion() {
        return new GetVersionOper(reqSpec);
    }

    /**
     * Customise request specification
     * @param consumer consumer
     * @return api
     */
    public UtilitiesApi reqSpec(Consumer<RequestSpecBuilder> consumer) {
        consumer.accept(reqSpec);
        return this;
    }

    /**
     * 
     * Returns healthcheck information about the system
     *
     */
    public static class GetHealthcheckOper {

        public static final Method REQ_METHOD = GET;
        public static final String REQ_URI = "/healthcheck";

        private RequestSpecBuilder reqSpec;
        private ResponseSpecBuilder respSpec;

        public GetHealthcheckOper(RequestSpecBuilder reqSpec) {
            this.reqSpec = reqSpec;
            reqSpec.setAccept("application/json");
            this.respSpec = new ResponseSpecBuilder();
        }

        /**
         * GET /healthcheck
         * @param handler handler
         * @param <T> type
         * @return type
         */
        public <T> T execute(Function<Response, T> handler) {
            return handler.apply(RestAssured.given().spec(reqSpec.build()).expect().spec(respSpec.build()).when().request(REQ_METHOD, REQ_URI));
        }

        /**
         * Customise request specification
         * @param consumer consumer
         * @return operation
         */
        public GetHealthcheckOper reqSpec(Consumer<RequestSpecBuilder> consumer) {
            consumer.accept(reqSpec);
            return this;
        }

        /**
         * Customise response specification
         * @param consumer consumer
         * @return operation
         */
        public GetHealthcheckOper respSpec(Consumer<ResponseSpecBuilder> consumer) {
            consumer.accept(respSpec);
            return this;
        }
    }
    /**
     * 
     * Returns the current version of the API Playground being run
     *
     */
    public static class GetVersionOper {

        public static final Method REQ_METHOD = GET;
        public static final String REQ_URI = "/version";

        private RequestSpecBuilder reqSpec;
        private ResponseSpecBuilder respSpec;

        public GetVersionOper(RequestSpecBuilder reqSpec) {
            this.reqSpec = reqSpec;
            reqSpec.setAccept("application/json");
            this.respSpec = new ResponseSpecBuilder();
        }

        /**
         * GET /version
         * @param handler handler
         * @param <T> type
         * @return type
         */
        public <T> T execute(Function<Response, T> handler) {
            return handler.apply(RestAssured.given().spec(reqSpec.build()).expect().spec(respSpec.build()).when().request(REQ_METHOD, REQ_URI));
        }

        /**
         * Customise request specification
         * @param consumer consumer
         * @return operation
         */
        public GetVersionOper reqSpec(Consumer<RequestSpecBuilder> consumer) {
            consumer.accept(reqSpec);
            return this;
        }

        /**
         * Customise response specification
         * @param consumer consumer
         * @return operation
         */
        public GetVersionOper respSpec(Consumer<ResponseSpecBuilder> consumer) {
            consumer.accept(respSpec);
            return this;
        }
    }
}
