/*
 * Best Buy API Playground
 * A sample dataset and API for you to experiment with.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@bestbuy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Assert;
import org.openapitools.client.model.Category;
import org.openapitools.client.model.ErrorModel;
import org.openapitools.client.ApiClient;
import org.openapitools.client.api.CategoriesApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;
import static org.openapitools.client.GsonObjectMapper.gson;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private CategoriesApi api;

    @Before
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("http://localhost:3030"))).categories();
    }

    /**
     * Empty response
     */
    @Test
    public void shouldSee200AfterAddCategory() {
        Category category = null;
        category.setId("8888");
        category.setName("shreyansh");
        api.addCategory()
                .body(category).execute(r -> r.prettyPeek());
    }

    /**
     * Unexpected error
     */
    @Test
    public void shouldSee400AfterAddCategory() {
        Category category = null;
        api.addCategory()
                .body(category).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Category deleted
     */
    @Test
    public void shouldSee200AfterDeletecategory() {
        Long id = null;
        api.deletecategory()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unexpected error
     */
    @Test
    public void shouldSee400AfterDeletecategory() {
        Long id = null;
        api.deletecategory()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Category response
     */
    @Test
    public void shouldSee200AfterFindCategories() {
        Integer $limit = null;
        Integer $skip = null;
        api.findCategories().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindCategories() {
        Integer $limit = null;
        Integer $skip = null;
        api.findCategories().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Category response
     */
    @Test
    public void shouldSee200AfterFindCategoryById() {
        Long id = null;
        api.findCategoryById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindCategoryById() {
        Long id = null;
        api.findCategoryById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Category response
     */
    @Test
    public void shouldSee200AfterUpdateCategoryById() {
        Long id = null;
        Category category = null;
        api.updateCategoryById()
                .idPath(id)
                .body(category).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterUpdateCategoryById() {
        Long id = null;
        Category category = null;
        api.updateCategoryById()
                .idPath(id)
                .body(category).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}