/*
 * Best Buy API Playground
 * A sample dataset and API for you to experiment with.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@bestbuy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ErrorModel;
import org.openapitools.client.model.Service;
import org.openapitools.client.ApiClient;
import org.openapitools.client.api.ServicesApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;
import static org.openapitools.client.GsonObjectMapper.gson;

/**
 * API tests for ServicesApi
 */
@Ignore
public class ServicesApiTest {

    private ServicesApi api;

    @Before
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("http://localhost:3030"))).services();
    }

    /**
     * Empty response
     */
    @Test
    public void shouldSee200AfterAddService() {
        Service service = null;
        api.addService()
                .body(service).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * unexpected error
     */
    @Test
    public void shouldSee400AfterAddService() {
        Service service = null;
        api.addService()
                .body(service).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Service deleted
     */
    @Test
    public void shouldSee200AfterDeleteservice() {
        Long id = null;
        api.deleteservice()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unexpected error
     */
    @Test
    public void shouldSee400AfterDeleteservice() {
        Long id = null;
        api.deleteservice()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Service response
     */
    @Test
    public void shouldSee200AfterFindServiceById() {
        Long id = null;
        api.findServiceById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindServiceById() {
        Long id = null;
        api.findServiceById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Service response
     */
    @Test
    public void shouldSee200AfterFindServices() {
        Integer $limit = null;
        Integer $skip = null;
        api.findServices().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindServices() {
        Integer $limit = null;
        Integer $skip = null;
        api.findServices().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Service response
     */
    @Test
    public void shouldSee200AfterUpdateServiceById() {
        Long id = null;
        Service service = null;
        api.updateServiceById()
                .idPath(id)
                .body(service).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterUpdateServiceById() {
        Long id = null;
        Service service = null;
        api.updateServiceById()
                .idPath(id)
                .body(service).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}