/*
 * Best Buy API Playground
 * A sample dataset and API for you to experiment with.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: developer@bestbuy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ErrorModel;
import org.openapitools.client.model.Store;
import org.openapitools.client.ApiClient;
import org.openapitools.client.api.StoresApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.junit.Before;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;
import static org.openapitools.client.GsonObjectMapper.gson;

/**
 * API tests for StoresApi
 */
@Ignore
public class StoresApiTest {

    private StoresApi api;

    @Before
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("http://localhost:3030"))).stores();
    }

    /**
     * Empty response
     */
    @Test
    public void shouldSee200AfterAddStore() {
        Store store = null;
        api.addStore()
                .body(store).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unexpected error
     */
    @Test
    public void shouldSee400AfterAddStore() {
        Store store = null;
        api.addStore()
                .body(store).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Store deleted
     */
    @Test
    public void shouldSee200AfterDeletestore() {
        Long id = null;
        api.deletestore()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * unexpected error
     */
    @Test
    public void shouldSee400AfterDeletestore() {
        Long id = null;
        api.deletestore()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Store response
     */
    @Test
    public void shouldSee200AfterFindStoreById() {
        Long id = null;
        api.findStoreById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindStoreById() {
        Long id = null;
        api.findStoreById()
                .idPath(id).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Store response
     */
    @Test
    public void shouldSee200AfterFindStores() {
        Integer $limit = null;
        Integer $skip = null;
        api.findStores().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterFindStores() {
        Integer $limit = null;
        Integer $skip = null;
        api.findStores().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * Store response
     */
    @Test
    public void shouldSee200AfterUpdateStoreById() {
        Long id = null;
        Store store = null;
        api.updateStoreById()
                .idPath(id)
                .body(store).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Error
     */
    @Test
    public void shouldSee400AfterUpdateStoreById() {
        Long id = null;
        Store store = null;
        api.updateStoreById()
                .idPath(id)
                .body(store).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}